"""Grading protocol + types (GR-1). This module's package is the ONE plugin seam (P7).

A grader is keyed on subject. The answer_key is CURATED (P2) — never generated by an
LLM. Generative freedom is confined to explanation, where mistakes are minor and
visible; the assess path must be trustworthy.
"""

from dataclasses import dataclass
from typing import Protocol, runtime_checkable


@dataclass(frozen=True)
class Item:
    skill_key: str
    prompt: str
    answer_key: str  # CURATED (P2) — not produced by an LLM
    rubric: str | None = None
    subject_key: str = "math"


@dataclass(frozen=True)
class GradeResult:
    correct: bool
    feedback: str
    confidence: float  # 1.0 = deterministically checked; < 1.0 = needs teacher review


@runtime_checkable
class GraderStrategy(Protocol):
    subject_key: str

    def grade(self, answer: str, item: Item) -> GradeResult: ...
