import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
// Design tokens from the Stitch "Helvetia Learning / EduSovereign" system
// (docs/stitch-design/.../helvetia_learning/DESIGN.md). Material-3 token names.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2f3034",
        "primary-container": "#2d4c7e",
        "on-secondary-fixed-variant": "#004f52",
        "surface-bright": "#faf9fe",
        "error-container": "#ffdad6",
        outline: "#747780",
        "inverse-on-surface": "#f1f0f5",
        "tertiary-fixed-dim": "#ffb95f",
        "on-error-container": "#93000a",
        "primary-fixed": "#d7e3ff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-background": "#1a1b1f",
        "secondary-fixed": "#9ef0f3",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-container": "#ffab31",
        "inverse-primary": "#aac7ff",
        "on-surface-variant": "#43474f",
        surface: "#faf9fe",
        tertiary: "#4d2f00",
        "tertiary-fixed": "#ffddb8",
        "on-secondary-fixed": "#002021",
        "secondary-container": "#9beef0",
        "on-surface": "#1a1b1f",
        "surface-dim": "#dad9de",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#82d4d7",
        "surface-container-low": "#f4f3f8",
        "surface-variant": "#e3e2e7",
        "primary-fixed-dim": "#aac7ff",
        "on-primary-container": "#a0bdf7",
        "on-primary-fixed-variant": "#274778",
        "surface-container-high": "#e8e7ec",
        "on-secondary": "#ffffff",
        primary: "#113566",
        "outline-variant": "#c4c6d0",
        "on-primary": "#ffffff",
        "surface-tint": "#405e92",
        secondary: "#00696c",
        "surface-container-highest": "#e3e2e7",
        "tertiary-container": "#6c4300",
        "on-primary-fixed": "#001b3e",
        "surface-container": "#eeedf2",
        background: "#faf9fe",
        "on-secondary-container": "#016e71",
        "on-tertiary": "#ffffff",
        "info-blue": "#005cbb",
        "warning-amber": "#6a3e00",
        "warning-amber-container": "#ffdcbe",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.25rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        gutter: "16px",
        unit: "4px",
        sm: "8px",
        md: "16px",
        xs: "4px",
        "container-margin": "24px",
        lg: "24px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        caption: ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "title-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        caption: ["12px", { lineHeight: "1.2", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" }],
      },
      boxShadow: {
        ambient: "0px 4px 20px rgba(45, 76, 126, 0.08)",
      },
    },
  },
  plugins: [forms],
};
