"""Curated assessment items (P2): the answer keys the assess path trusts.

These are hand-curated, NOT generated by an LLM — a hallucinated key would teach a
child the wrong thing. Referenced by the agent's assess node via load_item(item_ref).
A richer store (file/DB-backed, per subject) can replace this dict later without
changing the interface; the curation requirement stays.
"""

from its.grading.base import Item

_CURATED: dict[str, Item] = {
    "expand-x-plus-1-squared": Item(
        skill_key="complete-the-square",
        subject_key="math",
        prompt="Multipliziere aus: (x+1)^2",
        answer_key="x**2 + 2*x + 1",
    ),
    "complete-square-x2-6x": Item(
        skill_key="complete-the-square",
        subject_key="math",
        prompt="Schreibe x^2 + 6x als vollständiges Quadrat plus Restterm.",
        answer_key="(x+3)**2 - 9",
    ),
    "factor-x2-5x-6": Item(
        skill_key="quadratic-formula",
        subject_key="math",
        prompt="Faktorisiere: x^2 + 5x + 6",
        answer_key="(x+2)*(x+3)",
    ),
}


def load_item(item_ref: str) -> Item:
    """Return the curated Item for item_ref, or raise LookupError (-> 404 at the API)."""
    try:
        return _CURATED[item_ref]
    except KeyError as e:
        raise LookupError(f"no curated item '{item_ref}'") from e
